import { Bell, Bus, CalendarDays, Clock3, MapPin, TicketCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHeader from '../../components/common/PageHeader';
import StatCard from '../../components/common/StatCard';
import Badge from '../../components/common/Badge';
import { notifications, reservations, trips } from '../../data/mock';
import { useAuth } from '../../hooks/useAuth';

export default function StudentDashboard(){
 const {user}=useAuth(); const upcoming=trips[0];
 return <><PageHeader title={`Good morning, ${user?.name?.split(' ')[0] ?? 'Student'} 👋`} subtitle="Here is what is happening with your campus shuttle today."/>
 <div className="hero-panel"><div className="hero-copy"><span className="kicker" style={{color:'#aaf5e8'}}>Smart campus mobility</span><h2>Your next ride is ready.</h2><p>{upcoming.routeName} departs at {upcoming.departure}. Reserve early to secure a seat and keep your QR pass ready for boarding.</p><div className="hero-actions"><Link className="btn primary" to="/student/search">Find a shuttle</Link><Link className="btn secondary" to="/student/track">Track my bus</Link></div></div><div className="hero-visual">🚌</div></div>
 <div className="grid cols-4" style={{marginTop:18}}><StatCard icon={TicketCheck} label="Active reservations" value="1" hint="1 upcoming trip"/><StatCard icon={Bus} label="Available shuttles" value="6" tone="blue" hint="3 routes near you"/><StatCard icon={Clock3} label="Next departure" value="07:30" tone="orange" hint="Campus → Uttara"/><StatCard icon={Bell} label="Unread alerts" value="2" tone="red" hint="1 delay notice"/></div>
 <div className="grid cols-3" style={{marginTop:18}}><section className="card span-2"><div className="card-head"><div><h3>Upcoming trips</h3><p>Your scheduled rides and seat status</p></div><Link className="btn ghost sm" to="/student/reservations">View all</Link></div>{trips.slice(0,2).map(t=><div className="trip-card" key={t.id} style={{marginBottom:10}}><div className="trip-top"><div><div className="trip-route">{t.routeName}</div><span className="muted" style={{fontSize:10.5}}>{t.date} • {t.busNumber}</span></div><Badge value={t.status}/></div><div className="trip-meta"><div><small>Departure</small><b>{t.departure}</b></div><div><small>Arrival</small><b>{t.arrival}</b></div><div><small>Available</small><b>{t.seatsAvailable} seats</b></div><div><small>Driver</small><b>{t.driverName}</b></div></div><div className="progress"><span style={{width:`${((t.capacity-t.seatsAvailable)/t.capacity)*100}%`}}/></div></div>)}</section>
 <section className="card"><div className="card-head"><div><h3>Recent notifications</h3><p>Latest shuttle updates</p></div></div><div className="list">{notifications.map(n=><div className="list-item" key={n.id}><div className="list-main"><div className="list-icon"><Bell size={16}/></div><div className="list-copy"><b>{n.title}</b><span>{n.message}</span></div></div></div>)}</div><Link className="btn secondary" style={{width:'100%',marginTop:12}} to="/student/notifications">All notifications</Link></section></div>
 <div className="grid cols-2" style={{marginTop:18}}><section className="card"><div className="card-head"><div><h3>Current reservation</h3><p>Boarding information</p></div><Badge value={reservations[0].status}/></div><div className="list"><div className="list-item"><div className="list-main"><div className="list-icon"><MapPin size={16}/></div><div className="list-copy"><b>{reservations[0].route}</b><span>{reservations[0].date} • {reservations[0].time}</span></div></div></div><div className="list-item"><div className="list-main"><div className="list-icon"><CalendarDays size={16}/></div><div className="list-copy"><b>{reservations[0].bus} • Seat {reservations[0].seat}</b><span>{reservations[0].reservationNo}</span></div></div></div></div><Link className="btn primary" to="/student/qr-pass">Open QR boarding pass</Link></section><section className="card"><div className="card-head"><div><h3>Quick actions</h3><p>Common shuttle tasks</p></div></div><div className="grid cols-2"><Link className="btn secondary" to="/student/search"><Bus size={16}/> Search shuttle</Link><Link className="btn secondary" to="/student/schedule"><CalendarDays size={16}/> View schedule</Link><Link className="btn secondary" to="/student/feedback"><Bell size={16}/> Feedback</Link><Link className="btn secondary" to="/student/report-issue"><MapPin size={16}/> Report issue</Link></div></section></div></>;
}
