import { Bus, MapPinned, QrCode, ShieldCheck } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import type { UserRole } from '../../types/user';

export default function Login(){
 const [role,setRole]=useState<UserRole>('student'); const [email,setEmail]=useState('student@unimove.edu'); const [password,setPassword]=useState('password'); const [busy,setBusy]=useState(false); const {login}=useAuth(); const nav=useNavigate(); const loc=useLocation();
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);await login(email,password,role);const from=(loc.state as {from?:string}|null)?.from;nav(from||`/${role}`);};
 const switchRole=(r:UserRole)=>{setRole(r);setEmail(r==='student'?'student@unimove.edu':'admin@unimove.edu')};
 return <div className="auth-page"><section className="auth-showcase"><div className="auth-showcase-content"><div className="brand"><span className="brand-mark"><Bus size={21}/></span><span>Uni<span>Move</span></span></div><h1>Campus mobility,<br/>made effortless.</h1><p>Search shuttles, reserve seats, board with QR and follow buses in real time from one clean university transport experience.</p><div className="auth-feature-grid"><div className="auth-feature"><MapPinned size={16}/> Live shuttle tracking</div><div className="auth-feature"><QrCode size={16}/> QR boarding pass</div><div className="auth-feature"><Bus size={16}/> Smart reservations</div><div className="auth-feature"><ShieldCheck size={16}/> Role-based access</div></div></div></section><section className="auth-panel"><form className="auth-box" onSubmit={submit}><Link to="/login" className="brand"><span className="brand-mark"><Bus size={20}/></span><span>Uni<span>Move</span></span></Link><h2>Welcome back</h2><p>Sign in to your shuttle management portal.</p><div className="role-tabs"><button type="button" className={role==='student'?'active':''} onClick={()=>switchRole('student')}>Student</button><button type="button" className={role==='admin'?'active':''} onClick={()=>switchRole('admin')}>Admin</button></div><div className="form-group"><label>Email address</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="form-group" style={{marginTop:12}}><label>Password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="btn primary" disabled={busy}>{busy?'Signing in...':'Sign in'}</button><div className="demo-note">Demo frontend: choose Student or Admin and use any password. The authentication service is ready to be connected to the Node/Express API later.</div><p style={{textAlign:'center',marginTop:18}}>New student? <Link style={{color:'var(--primary)',fontWeight:700}} to="/register">Create account</Link></p></form></section></div>;
}
